name: Release

on:
  workflow_dispatch:

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write # for github releases
      id-token: write # for keyless signing

    steps:
      - name: Validate Tag
        run: |
          if [[ "${GITHUB_REF:0:10}" != refs/tags/ ]]; then
            echo 'Full Release workflow must be run with a tag, not a branch.'
            exit 1
          fi
          tag="${GITHUB_REF:10}"
          if ! grep -E '^v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' <<<"$tag"; then
            echo 'Invalid tag format. Must be semver with only major, minor, and patch, e.g. v1.2.3'
            exit 1
          fi

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.22'

      - name: Install cosign for signatures
        uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 # v3.9.2

      - name: Install syft for sboms
        uses: anchore/sbom-action/download-syft@7b36ad622f042cab6f59a75c2ac24ccb256e9b45 # v0.20.4

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          version: '~> v2.4.8'
          args: --verbose release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.event.inputs.tag }}
        continue-on-error: false
