name: Gemini AI Code Review
on:
  pull_request_target:
    types: [opened]

permissions:
  contents: none
  pull-requests: none
  issues: none
  actions: none

jobs:
  call_gemini_review:
    name: Gemini review
    uses: complytime/org-infra/.github/workflows/reusable_gemini_review.yml@main
    permissions:
      contents: read
      pull-requests: write